[build-system]
requires = [
    "setuptools>=61.0",
    "setuptools_scm[toml]>=8.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "seguin_loom_server"
dynamic = ["version"]
description = "Web server that drives a Séguin dobby loom"
readme = "README.md"
authors = [
  { name="Russell Owen", email="r3owen@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.11"

# Needed due to including py.typed below
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"seguin_loom_server" = ["py.typed", "display.css", "display.html_template", "display.js"]

[project.scripts]
run_seguin = "seguin_loom_server.main:start_seguin_loom_server"

[project.urls]
Homepage = "https://github.com/r-owen/seguin_loom_server"
Issues = "https://github.com/r-owen/seguin_loom_server/issues"

[tool.setuptools_scm]
write_to = "src/seguin_loom_server/version.py"
write_to_template = """
# Generated by setuptools_scm
__all__ = ["__version__"]
__version__ = "{version}"
"""
